### ISSUE TITLE
City_Name API call not specific enough

### ISSUE THREAD

**Issue by smkirchn** [tapecanvas/WatchyDefaultFahrenheit#1]
The problem lies in the Watchy.cpp file. Specifically line 596

`String weatherQueryURL = String(OPENWEATHERMAP_URL) + String(CITY_NAME) + String(",") + String(COUNTRY_CODE) + String("&units=") + String(TEMP_UNIT) + String("&appid=") + String(OPENWEATHERMAP_APIKEY);`

Changing the above line to:

`String weatherQueryURL = String(OPENWEATHERMAP_URL) + String(CITY_ID) + String("&units=") + String(TEMP_UNIT) + String("&appid=") + String(OPENWEATHERMAP_APIKEY);`

Then changing the weather api section of the config.h file to:

//weather api
#define CITY_ID "5128581" //find your city id by searching your city on https://openweathermap.org/ ,your city id will appear in the address bar. Ex: https://openweathermap.org/city/5128581  <-- the number is your city id
#define OPENWEATHERMAP_APIKEY "f058fe1cad2afe8e2ddc5d063a64cecb" //use your own API key :)
#define OPENWEATHERMAP_URL "http://api.openweathermap.org/data/2.5/weather?id="
#define TEMP_UNIT "imperial" //use "metric" for Celsius"
#define WEATHER_UPDATE_INTERVAL 30 //minutes

Doing this and following the rest of your instructions worked for me!

**Comment by tapecanvas** [comment]
Checked it all out. Works well. Thanks for helping out! I have updated the instructions to include your changes and added a little more info for newcomers. Closing this issue now.
